Milestone 2 1st Draft
Virtana/robot_camera_calibration pull request #10
Opened 2019-07-25 18:52 UTC by DAA2310

Milestone 2 
-Repurposing for YAML generation, class inclusion and initial refactoring.

Milestone 1
-size (height and width) adaptation. 

README update

2019-08-06 15:30 UTC, Keyran-H requested changes
Good work! I did a high level pass. Left a couple comments for you to address while I take a closer look.

2019-08-06 15:30 UTC, Keyran-H commented on real_preprocessing/README.md
> +The **apriltag\_ros** library was forked and modified to publish pixel coordinates of detected tags on the /tag_detections rostopic. This was done as an alternative method to the homography concepts
"used" repeated twice

2019-08-06 15:30 UTC, Kiran-H-github commented on real_preprocessing/src/camera_pose.cpp
> +}
Add a new line at the end of file.

2019-08-06 15:30 UTC, Kiran-H-github commented on real_preprocessing/src/camera_pose.cpp
> +    while (fileReader(file) != 3)
The same file is being used in the same function over and over. Just store the fileReader(file) in a variable and reuse this.

2019-08-06 15:30 UTC, Kiran-H-github commented on real_preprocessing/src/camera_pose.cpp
> +      if (fileReader(file) == 0) //world tag present
Look at enumerations or macros for flag comparisons

2019-08-06 15:30 UTC, Kiran-H-github commented on real_preprocessing/src/camera_pose.cpp
> +  void unknownPoll()
Nit: Too ambiguous, maybe "unknownFilepoll" or "checkUnknownfiles"

2019-08-06 15:30 UTC, Kiran-H-github commented on real_preprocessing/src/camera_pose.cpp
> +    if(world_pres==0)
Nit: My preference but i would suggest for booleans just use either True or False.

2019-08-06 15:49 UTC, Kiran-H-github commented on real_preprocessing/src/camera_pose.cpp
> +    intrinsicLoad(cam_matrix, distCoeffs);
Nit: I see here that you load in constant values every time this function is called. You can just call intrinsicLoad in the constructor and save the parameters in constants according to the cpp ref guidelines.

2019-08-15 14:27 UTC, Keyran-H requested changes
I am not done yet, still a work in progress. Make these changes and I will have another pass

2019-08-15 14:27 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +        if (std::find(w_T_tags_id.begin(), w_T_tags_id.end(), tags_pix["detections"][i]["targetID"].as<int>()) !=w_T_tags_id.end())
Explore:
w_T_tags_id.find(tags_pix["detections"][i]["targetID"].as<int>()) != w_T_tags_id.end()

2019-08-15 14:27 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +  int file, world_tag;
world_tag is a constant

2019-08-15 14:27 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +    int known_tag_in_file;
Capture somewhere that this is an output of the fileReader.

2019-08-15 14:27 UTC, Kiran-H-github commented on real_preprocessing/src/camera_pose.cpp
> +        targetDump(w_T_tags_id,w_T_tags_size,w_T_tags_trans);
I think it makes sense to dump the values outside the while loop

2019-08-15 14:27 UTC, Kiran-H-github commented on real_preprocessing/src/camera_pose.cpp
> +  void fileStream()
Explore this code instead for this function:
int known_tag_in_file;
int status = fileReader(file,known_tag_in_file);
if (status != NO_FILE)
{
 if ((status == WORLD_PRES)||(status == KNOWN_TAG)) //world tag or known tags present
 {
  tagCalc(file,known_tag_in_file,status);
  unknownFilepoll();
 }
 if (status == UNKNOWN) //all unknown tags
 {
  unknown_file.push_back(file); //stores file with all unknown tags
 }
 file++
}
targetDump(w_T_tags_id,w_T_tags_size,w_T_tags_trans);

2019-08-16 15:38 UTC, Keyran-H requested changes
Still a work in progress and not done yet. Overall, you should be consistent with your spacing and also your transform variable naming (for example either tagTcam or tag_T_cam).

2019-08-16 15:38 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +  std::string pathLoad(int filenum=-1)
Put a summary of the function above the function

2019-08-16 15:38 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +  void worldAppend(int filenum, Eigen::MatrixXd wTcam)
Nit: Be consistent throughout. Either "wTcam" or "w_T_cam".

2019-08-16 15:38 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +  //populates existing detection YAML fules with world_T_cam transforms
Nit: "// Appends the existing detection YAML files with the world_T_cam transform"

2019-08-16 15:38 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +  std::string pathLoad(int filenum=-1)
I don't really agree with how this function works and how it is being used. This function should be called once and then the full file path should be returned. I would suggest adding in an additional flag as per our small discussion and create some branching to return the desired path.

2019-08-16 15:38 UTC, Kiran-H-github commented on real_preprocessing/src/camera_pose.cpp
> +  Eigen::MatrixXd tagTcam(int loc, int filenum)
Nit: loc is too ambiguous, how about tag_loc

2019-08-16 15:38 UTC, Kiran-H-github commented on real_preprocessing/src/camera_pose.cpp
> +  //Calculates w_T_tag for all unknown tags in a file
This is stale right

2019-08-16 15:38 UTC, Kiran-H-github commented on real_preprocessing/src/camera_pose.cpp
> +  void tagCalc(int filenum, int loc, int file_type)
Again, loc is too ambiguous. How about tag_loc

2019-08-16 15:38 UTC, Kiran-H-github commented on real_preprocessing/src/camera_pose.cpp
> +    if(file_type==WORLD_PRES)
Nit: else if

2019-08-16 15:38 UTC, Kiran-H-github commented on real_preprocessing/src/camera_pose.cpp
> +  void tagCalc(int filenum, int loc, int file_type)
I feel like the logic in this function could be done better.

2019-08-16 15:38 UTC, Kiran-H-github commented on real_preprocessing/src/camera_pose.cpp
> +      if (status == UNKNOWN) //all unknown tags
Nit: Use else if.

2019-08-19 15:21 UTC, sarika93 reviewed
Minor comments for now that I'm submitting so you can address these along with Kiran's change requests. I'll do a more in-depth review when those go in.

2019-08-19 15:21 UTC, sarika93 commented on real_preprocessing/src/camera_pose.cpp
> +#define WORLD_PRES 0
Nit: leave a line space between the includes and defines

2019-08-19 15:21 UTC, sarika93 commented on real_preprocessing/src/camera_pose.cpp
> +    NH.getParam("/camera_matrix/data", intrinsic);
getParam returns false if a param if not found and true if found. Use this behavior to output error messages to a user if these values are not set since these are mandatory for operation. See [here](http://wiki.ros.org/roscpp/Overview/Parameter%20Server) for an example of how this is used.

2019-08-19 15:21 UTC, sarika93 commented on real_preprocessing/src/camera_pose.cpp
> +    NH.getParam("/distortion_coefficients/data", intrinsic);
Same as the above getParam comment.

2019-08-19 15:21 UTC, sarika93 commented on real_preprocessing/src/camera_pose.cpp
> +
This is a huge file, and ideally should be split into a header files with all declarations and a cpp with the actual function definitions. In the interest of time, add a TODO that says something like "split this file into a .h and .cpp file in a later refactor".

2019-08-19 15:21 UTC, sarika93 commented on real_preprocessing/src/camera_pose.cpp
> +  std::vector<int> unknown_file;
This is a bad name. Rename to "unreferenced_targets_file". This way it is more clear that this file has no targets that we are able to reference to world.

2019-08-19 15:21 UTC, sarika93 commented on real_preprocessing/src/camera_pose.cpp
> +  int file, kworld_tag;
"file" is a vague name. what file?

2019-08-22 21:23 UTC, Keyran-H requested changes
Did another quick pass. I think your code structure is fine, but i think your code is severely lacking comments and need some different variable renaming. Also generally, the comments for the functions could be reworded to be more specific.

2019-08-22 21:23 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +      if (filenum == 0)//polling first file?
Delete this comment.

2019-08-22 21:23 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +      YAML::Node tags_pix = YAML::LoadFile(pathLoad(filenum));
"tags_pix" is not a very good name. Maybe "YAML_handle" or something more descriptive.

2019-08-22 21:23 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +      for (int i = 0; i < tags_pix["detections"].size(); ++i)
I don't agree with these variable names. Correct me if I am wrong but I think that "i" should be the tag index within the file so maybe "tag_index". Also, "tags_pix["detections"].size()" should be saved in a variable called "total_tags_in_file" or along those lines.

2019-08-22 21:23 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +        if (std::find(w_T_tags_id.begin(), w_T_tags_id.end(), tags_pix["detections"][i]["targetID"].as<int>()) !=w_T_tags_id.end())
You **NEED** to document why you are checking within w_T_tags_id and kworld_tag separately even though kworld_tag is already in w_T_tags_id.

2019-08-22 21:23 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +  //Polls for unknown files to be reprocessed
This is too vague. How about "Reprocess files with unknown tags"

2019-08-22 21:23 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +  std::string pathLoad(int filenum=-1, std::string file_type="DETECTION")
This is not really loading a path. You are more less getting a file path. How about "getFilepath".

2019-08-22 21:23 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +    ROS_ERROR("Camera intrinsics not loaded to parameter server!");
indent this line.

2019-08-22 21:23 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +  //populates world tag data based on first image taken
Mention that the first tag from the first image taken is assumed to be the world.

2019-08-22 21:23 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +  //Appends the existing detection YAML files with the world_T_cam transforms
Appends the world_T_cam transform to the respective detection YAML file.

2019-08-22 21:23 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +    fout.open(pathLoad(0,"TARGET"));
Check if you can use named arguments in c++ so that you don't need to enter an int when you are trying to get the "TARGET" filepath.

2019-08-22 21:23 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +  void targetDump(std::vector<int>& id, std::vector<double>& size, std::vector<Eigen::MatrixXd>& trans)
These variables need more specific names

2019-08-22 21:23 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +    YAML::Node tags_pix = YAML::LoadFile(pathLoad(filenum));
Again, bad name. Change all instances.

2019-08-22 21:23 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +    for (int i = 0; i < tags_pix["detections"].size(); ++i)
i and tags_pix["detections"].size() are not great names. Read further comments for suggestions.

2019-08-22 21:23 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +  void tagCalc(int filenum, int tag_loc)
It's not really a tag_loc right, it's a tag_id within a file that you are passing in. How about "tag_id" or "file_tag_id" instead.

2019-08-23 21:09 UTC, Keyran-H requested changes
Looks good! I think these should be the final bit of changes. Comments inline

2019-08-23 21:09 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +  std::string getFilepath(int filenum = TARGET)
I think that this function is a bit confusing so just break it up. Create a function to return the basepath, create a function to return the detection file given a number and have no function for the targets.yaml since it is being used in one place only.

2019-08-23 21:09 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +    for (int tag_index = 0; tag_index < total_tags_in_file; ++tag_index)
I think you should add comments summarizing your logic here.

2019-08-23 21:09 UTC, Keyran-H commented on real_preprocessing/src/camera_pose.cpp
> +      /*Despite the inclusion of the world tag in w_T_tags_id and its associated vectors, presence of the world tag is prioritised in file reading.
These comments should be placed above the if statements.

2019-08-23 21:09 UTC, Kiran-H-github commented on real_preprocessing/src/camera_pose.cpp
> +  public:
Any particular reason you shifted the constructor down here?

2019-08-29 12:42 UTC, DAA2310 commented on real_preprocessing/src/camera_pose.cpp
> +  public:
There was an issue when the constructor was made private. I'd restructure to suit.

2019-08-30 12:57 UTC, Keyran-H approved these changes
LGTM, the README would be fixed in another PR.

2019-08-30 13:02 UTC, merged