Adding targets
Virtana/robot_camera_calibration pull request #5
Opened 2019-06-21 12:39 UTC by chris24sahadeo

Target class completed.

RViz works with a single target.

2019-06-23 23:56 UTC, vpradeep07 reviewed
Make sure to use a constant style throughout the project.  I'd suggest choosing one of the two options below:
* http://wiki.ros.org/CppStyleGuide
* https://google.github.io/styleguide/cppguide.html

2019-06-27 03:30 UTC, sarika93 requested changes
Remove camera.h and marker_layout.h. I tried running the simulator node with rviz, but nothing showed up for me. I'm probably doing something wrong, so we'll chat about that on Friday.

2019-06-27 03:30 UTC, sarika93 commented on rviz_simulator/include/rviz_simulator/target.h
> +#ifndef TARGET
See [here](http://wiki.ros.org/CppStyleGuide#A.23ifndef_guards) for the ifndef format from the styleguide. This should be RVIZ_SIMULATOR_TARGET_H. This also applies to the define below.

2019-06-27 03:30 UTC, sarika93 commented on rviz_simulator/include/rviz_simulator/target.h
> +  float r_, g_, b_, a_, scale_;
Not obvious what r_, g_, b_ and a_ represent from these names (e.g. instead of "a_" use "marker_opacity_"). Alternatively, instead of r, g, b and a as individual float, use a single std_msgs::ColorRBGA object.

Give more descriptive names. "scale_" is the scale of what? Same applies to "name_" and "position_".

2019-06-27 03:30 UTC, sarika93 commented on rviz_simulator/include/rviz_simulator/target.h
> +  visualization_msgs::InteractiveMarker int_marker_;
target_marker_ is more descriptive name; particularly since there will also be camera markers.

2019-06-27 03:30 UTC, sarika93 commented on rviz_simulator/launch/simulate.launch
> +<launch>
Remove this file since this is empty. Add it to master only after it is populated.

2019-06-27 03:30 UTC, sarika93 commented on rviz_simulator/src/simulate.cpp
> +  // rviz_simulator::Target target2("ROSworld", "target_2", tf::Vector3(0, 3, 0), 0.5, 0.5, 0.5, 1.0, 1.0, server);
Remove stale comments.

2019-06-27 03:30 UTC, sarika93 commented on rviz_simulator/include/rviz_simulator/target.h
> +  visualization_msgs::Marker makeBox(visualization_msgs::InteractiveMarker& msg);
Use a more descriptive name e.g. makeTagMarker

2019-06-27 03:30 UTC, sarika93 commented on rviz_simulator/include/rviz_simulator/target.h
> +  visualization_msgs::InteractiveMarkerControl& makeBoxControl(visualization_msgs::InteractiveMarker& msg);
Use a more descriptive name e.g. makeTagMarkerControl

2019-06-27 03:30 UTC, sarika93 commented on rviz_simulator/src/simulate.cpp
> +#include "rviz_simulator/camera.h"
Empty file. Remove this as it is unused.

2019-06-27 03:30 UTC, sarika93 commented on rviz_simulator/src/one_marker.cpp
> +#include <ros/ros.h>
Remove this file since this is only used for testing out interactive markers.

2019-06-27 03:30 UTC, sarika93 commented on rviz_simulator/src/target.cpp
> +void Target::make6DofMarker(const tf::Vector3& positition)
Typo. Should be "position"

2019-06-27 03:30 UTC, sarika93 commented on rviz_simulator/src/target.cpp
> +  tf::pointTFToMsg(position_, this->int_marker_.pose.position);
position_ is only used here, and it is converted to a different format. Consider using geometry_msgs::Point message type instead of tf::Vector3 to avoid this conversion.

2019-06-27 03:30 UTC, sarika93 commented on rviz_simulator/src/target.cpp
> +  /// marker axis not fixed
Not clear what this comment is associated with.

2019-07-01 01:22 UTC, sarika93 approved these changes

2019-07-01 14:21 UTC, merged